version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Extensions.Configuration.AzureKeyVault
    versions:
    - 3.1.11
    - 3.1.12
    - 3.1.13
